from collections import defaultdict, deque
from ryu.base import app_manager
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, DEAD_DISPATCHER
from ryu.controller.handler import MAIN_DISPATCHER, set_ev_cls
from ryu.lib import hub
from ryu.lib.packet import ether_types, ethernet, packet
from ryu.ofproto import ofproto_v1_3
from ryu.topology import event
from ryu.topology.api import get_link, get_switch


class LinkFailureRecovery(app_manager.RyuApp):
    #Learning switch with dynamic shortest-path rerouting.

    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]

    # Smaller timeouts reduce stale forwarding state after topology changes.
    FLOW_PRIORITY = 100
    FLOW_IDLE_TIMEOUT = 60
    FLOW_HARD_TIMEOUT = 0
    MONITOR_INTERVAL = 5

    def __init__(self, *args, **kwargs):
        super(LinkFailureRecovery, self).__init__(*args, **kwargs)

        self.datapaths = {}
        self.mac_to_port = defaultdict(dict)          # dpid -> mac -> port
        self.host_locations = {}                      # mac -> (dpid, port)
        self.adjacency = defaultdict(dict)            # dpid -> neighbor_dpid -> out_port
        self.switch_ports = defaultdict(set)          # dpid -> all OpenFlow ports
        self.link_ports = defaultdict(set)            # dpid -> inter-switch ports
        self.installed_paths = {}                     # (src_mac, dst_mac) -> [dpid, ...]

        self.monitor_thread = hub.spawn(self._topology_monitor)

    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        #Install the table-miss flow so unknown traffic reaches PacketIn.
        datapath = ev.msg.datapath
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto

        match = parser.OFPMatch()
        actions = [
            parser.OFPActionOutput(
                ofproto.OFPP_CONTROLLER,
                ofproto.OFPCML_NO_BUFFER,
            )
        ]
        self._add_flow(datapath, 0, match, actions)
        self.logger.info("Switch connected: dpid=%s", datapath.id)

    @set_ev_cls(ofp_event.EventOFPStateChange, [MAIN_DISPATCHER, DEAD_DISPATCHER])
    def state_change_handler(self, ev):
        #Track currently connected switches by datapath ID.
        datapath = ev.datapath

        if ev.state == MAIN_DISPATCHER:
            if datapath.id not in self.datapaths:
                self.datapaths[datapath.id] = datapath
                self.logger.info("Registered datapath: dpid=%s", datapath.id)
        elif ev.state == DEAD_DISPATCHER:
            if datapath.id in self.datapaths:
                del self.datapaths[datapath.id]
                self.logger.warning("Unregistered datapath: dpid=%s", datapath.id)

    @set_ev_cls(event.EventSwitchEnter)
    def switch_enter_handler(self, ev):
        self.logger.info("Topology event: switch entered")
        self._refresh_topology()

    @set_ev_cls(event.EventSwitchLeave)
    def switch_leave_handler(self, ev):
        self.logger.warning("Topology event: switch left")
        self._refresh_topology()

    @set_ev_cls(event.EventLinkAdd)
    def link_add_handler(self, ev):
        link = ev.link
        src_dpid = link.src.dpid
        dst_dpid = link.dst.dpid
        src_port = link.src.port_no

        self.adjacency[src_dpid][dst_dpid] = src_port
        self.logger.info(
            "Link detected: s%s:%s -> s%s:%s",
            src_dpid,
            link.src.port_no,
            dst_dpid,
            link.dst.port_no,
        )
        self._refresh_topology()

    @set_ev_cls(event.EventLinkDelete)
    def link_delete_handler(self, ev):
        link = ev.link
        src_dpid = link.src.dpid
        dst_dpid = link.dst.dpid
        failed_edge = (src_dpid, dst_dpid)

        self.logger.warning(
            "Link failure occurs: s%s:%s -> s%s:%s",
            src_dpid,
            link.src.port_no,
            dst_dpid,
            link.dst.port_no,
        )

        self._refresh_topology()
        self._remove_link_from_graph(src_dpid, dst_dpid)
        self._recover_affected_paths(failed_edge)

    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev):
        #Learn hosts and install shortest-path forwarding rules.
        msg = ev.msg
        datapath = msg.datapath
        dpid = datapath.id
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto
        in_port = msg.match["in_port"]

        pkt = packet.Packet(msg.data)
        eth = pkt.get_protocol(ethernet.ethernet)

        if eth is None:
            return

        # Ignore LLDP frames generated by topology discovery.
        if eth.ethertype == ether_types.ETH_TYPE_LLDP:
            return

        src_mac = eth.src
        dst_mac = eth.dst

        if not self._is_link_port(dpid, in_port):
            self.mac_to_port[dpid][src_mac] = in_port
            self.host_locations[src_mac] = (dpid, in_port)

        if dst_mac in self.host_locations and src_mac in self.host_locations:
            dst_dpid, dst_port = self.host_locations[dst_mac]
            src_dpid, src_port = self.host_locations[src_mac]
            path = self._shortest_path(src_dpid, dst_dpid)

            if path:
                self._install_path(path, src_mac, dst_mac, src_port, dst_port)
                out_port = self._out_port_for_packet(path, dpid, dst_port)
            else:
                self.logger.warning(
                    "No alternate path available: %s at s%s -> %s at s%s",
                    src_mac,
                    src_dpid,
                    dst_mac,
                    dst_dpid,
                )
                return

            if out_port is not None:
                actions = [parser.OFPActionOutput(out_port)]
                self._send_packet_out(msg, actions)
        else:
            self._flood_to_access_ports(msg)

    def _topology_monitor(self):
        """Poll topology APIs so the local graph stays current."""
        while True:
            self._refresh_topology()
            hub.sleep(self.MONITOR_INTERVAL)

    def _refresh_topology(self):
        """Read switches and links from Ryu's topology service."""
        switches = get_switch(self, None)
        links = get_link(self, None)

        discovered = defaultdict(dict)
        switch_ports = defaultdict(set)
        link_ports = defaultdict(set)

        for switch in switches:
            dpid = switch.dp.id
            for port in switch.ports:
                if port.port_no < ofproto_v1_3.OFPP_MAX:
                    switch_ports[dpid].add(port.port_no)

        for link in links:
            discovered[link.src.dpid][link.dst.dpid] = link.src.port_no
            link_ports[link.src.dpid].add(link.src.port_no)

        self.adjacency = discovered
        self.switch_ports = switch_ports
        self.link_ports = link_ports

        switch_ids = sorted(switch.dp.id for switch in switches)
        link_count = len(links)
        self.logger.debug("Topology refreshed: switches=%s links=%s", switch_ids, link_count)

    def _remove_link_from_graph(self, src_dpid, dst_dpid):
        #Remove both directions of a failed physical link from adjacency.
        src_port = self._port_to_neighbor(src_dpid, dst_dpid)
        dst_port = self._port_to_neighbor(dst_dpid, src_dpid)
        self.adjacency[src_dpid].pop(dst_dpid, None)
        self.adjacency[dst_dpid].pop(src_dpid, None)
        self.link_ports[src_dpid].discard(src_port)
        self.link_ports[dst_dpid].discard(dst_port)

    def _recover_affected_paths(self, failed_edge):
        #Delete old flows and install alternate paths for affected host pairs.
        affected = []
        for host_pair, path in list(self.installed_paths.items()):
            if self._path_uses_edge(path, failed_edge):
                affected.append(host_pair)

        if not affected:
            self.logger.info("No installed host paths used failed link %s", failed_edge)
            return

        self.logger.warning("Affected paths: %s", affected)

        for src_mac, dst_mac in affected:
            self._delete_host_pair_flows(src_mac, dst_mac)
            self.installed_paths.pop((src_mac, dst_mac), None)

            if src_mac not in self.host_locations or dst_mac not in self.host_locations:
                continue

            src_dpid, src_port = self.host_locations[src_mac]
            dst_dpid, dst_port = self.host_locations[dst_mac]
            new_path = self._shortest_path(src_dpid, dst_dpid)

            if new_path:
                self._install_path(new_path, src_mac, dst_mac, src_port, dst_port)
                self.logger.info(
                    "New path installed after failure: %s -> %s via %s",
                    src_mac,
                    dst_mac,
                    self._format_path(new_path),
                )
            else:
                self.logger.error(
                    "No alternate path found after failure: %s -> %s",
                    src_mac,
                    dst_mac,
                )

    def _shortest_path(self, src_dpid, dst_dpid):
        """Return a shortest switch path using BFS."""
        if src_dpid == dst_dpid:
            return [src_dpid]

        visited = {src_dpid}
        queue = deque([[src_dpid]])

        while queue:
            path = queue.popleft()
            current = path[-1]

            for neighbor in sorted(self.adjacency.get(current, {})):
                if neighbor in visited:
                    continue

                next_path = path + [neighbor]
                if neighbor == dst_dpid:
                    return next_path

                visited.add(neighbor)
                queue.append(next_path)

        return None

    def _install_path(self, path, src_mac, dst_mac, src_port, dst_port):
        #Install match-action flows along a switch path.
        if not path:
            return

        for index, dpid in enumerate(path):
            datapath = self.datapaths.get(dpid)
            if datapath is None:
                self.logger.warning("Cannot install flow; datapath missing: s%s", dpid)
                continue

            if len(path) == 1:
                in_port = src_port
                out_port = dst_port
            elif index == 0:
                in_port = src_port
                out_port = self.adjacency[dpid][path[index + 1]]
            elif index == len(path) - 1:
                in_port = self.adjacency[dpid][path[index - 1]]
                out_port = dst_port
            else:
                in_port = self.adjacency[dpid][path[index - 1]]
                out_port = self.adjacency[dpid][path[index + 1]]

            parser = datapath.ofproto_parser
            match = parser.OFPMatch(
                in_port=in_port,
                eth_src=src_mac,
                eth_dst=dst_mac,
            )
            actions = [parser.OFPActionOutput(out_port)]
            self._add_flow(
                datapath,
                self.FLOW_PRIORITY,
                match,
                actions,
                idle_timeout=self.FLOW_IDLE_TIMEOUT,
                hard_timeout=self.FLOW_HARD_TIMEOUT,
            )

        self.installed_paths[(src_mac, dst_mac)] = path
        self.logger.info(
            "New path installed: %s -> %s via %s",
            src_mac,
            dst_mac,
            self._format_path(path),
        )

    def _delete_host_pair_flows(self, src_mac, dst_mac):
        #Remove stale flows for one host pair from all connected switches.
        for datapath in self.datapaths.values():
            parser = datapath.ofproto_parser
            ofproto = datapath.ofproto
            match = parser.OFPMatch(eth_src=src_mac, eth_dst=dst_mac)
            mod = parser.OFPFlowMod(
                datapath=datapath,
                command=ofproto.OFPFC_DELETE,
                out_port=ofproto.OFPP_ANY,
                out_group=ofproto.OFPG_ANY,
                priority=self.FLOW_PRIORITY,
                match=match,
            )
            datapath.send_msg(mod)

        self.logger.info("Removed stale flows: %s -> %s", src_mac, dst_mac)

    def _add_flow(
        self,
        datapath,
        priority,
        match,
        actions,
        idle_timeout=0,
        hard_timeout=0,
    ):
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto

        instructions = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS, actions)]
        mod = parser.OFPFlowMod(
            datapath=datapath,
            priority=priority,
            match=match,
            instructions=instructions,
            idle_timeout=idle_timeout,
            hard_timeout=hard_timeout,
        )
        datapath.send_msg(mod)

    def _send_packet_out(self, msg, actions):
        datapath = msg.datapath
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto

        data = None
        if msg.buffer_id == ofproto.OFP_NO_BUFFER:
            data = msg.data

        out = parser.OFPPacketOut(
            datapath=datapath,
            buffer_id=msg.buffer_id,
            in_port=msg.match["in_port"],
            actions=actions,
            data=data,
        )
        datapath.send_msg(out)

    def _flood_to_access_ports(self, msg):
        #Flood unknown or broadcast traffic only to host-facing ports.
        ingress_dpid = msg.datapath.id
        ingress_port = msg.match["in_port"]

        for dpid, datapath in self.datapaths.items():
            parser = datapath.ofproto_parser
            ofproto = datapath.ofproto
            access_ports = self.switch_ports.get(dpid, set()) - self.link_ports.get(dpid, set())

            actions = []
            for port in sorted(access_ports):
                if dpid == ingress_dpid and port == ingress_port:
                    continue
                actions.append(parser.OFPActionOutput(port))

            if not actions:
                continue

            data = None
            buffer_id = ofproto.OFP_NO_BUFFER
            in_port = ofproto.OFPP_CONTROLLER
            if dpid == ingress_dpid:
                buffer_id = msg.buffer_id
                in_port = ingress_port
                if msg.buffer_id == ofproto.OFP_NO_BUFFER:
                    data = msg.data
            else:
                data = msg.data

            out = parser.OFPPacketOut(
                datapath=datapath,
                buffer_id=buffer_id,
                in_port=in_port,
                actions=actions,
                data=data,
            )
            datapath.send_msg(out)

    def _is_link_port(self, dpid, port_no):
        return port_no in self.link_ports.get(dpid, set())

    def _port_to_neighbor(self, src_dpid, dst_dpid):
        return self.adjacency.get(src_dpid, {}).get(dst_dpid)

    def _out_port_for_packet(self, path, current_dpid, dst_port):
        """Choose the immediate output port for the PacketIn switch."""
        if current_dpid not in path:
            return None

        index = path.index(current_dpid)
        if index == len(path) - 1:
            return dst_port

        next_dpid = path[index + 1]
        return self.adjacency.get(current_dpid, {}).get(next_dpid)

    @staticmethod
    def _path_uses_edge(path, edge):
        #Check both directions because Ryu may report one directed edge.
        src_dpid, dst_dpid = edge
        for left, right in zip(path, path[1:]):
            if (left, right) == (src_dpid, dst_dpid):
                return True
            if (left, right) == (dst_dpid, src_dpid):
                return True
        return False

    @staticmethod
    def _format_path(path):
        return " -> ".join("s%s" % dpid for dpid in path)